name: Review Requested

on:
  pull_request:
    types: [review_requested]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  review-requested:
    runs-on: ubuntu-latest
    steps:
    - name: Create or Update Project Card
      uses: peter-evans/create-or-update-project-card@v2
      with:
        project-name: gmaif_workflows
        column-name: Review in progress
        issue-number: ${{ github.event.number }}
